services:
  back:
    image: ghcr.io/freeuni-digital-technologies/exam-schedules:main
    secrets:
      - secret.json
    env_file: .env.docker
    ports:
      - 3636:3636

  front:
    image: ghcr.io/freeuni-digital-technologies/exam-schedules-front:main
    env_file: .env.docker
    ports:
      - 80:3000

secrets:
  secret.json:
    file: ./secret.json